# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Use Case Podcast
email: usecasepod@gmail.com
description: Developers making a podcast about development!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://usecasepod.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true
future: false
twitter_username: usecasepod
github_username: usecasepod
disqus:
  enabled: true
  id: https-usecasepod-github-io
podcatchers:
  - name: Apple Podcasts
    url: https://podcasts.apple.com/us/podcast/use-case/id1481366213?uo=4
    img: apple_podcasts@2x.png
  - name: Spotify
    url: https://open.spotify.com/show/2bePoRcK7kDnO9nRRttVA7
    img: spotify@2x.png
  - name: Stitcher
    url: https://www.stitcher.com/podcast/use-case
    img: stitcher_dark@2x.png
  - name: Overcast
    url: https://overcast.fm/itunes1481366213/use-case
    img: overcast@2x.png
  - name: Google Podcasts
    url: https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy9jYjZkNzEwL3BvZGNhc3QvcnNz
    img: google_podcasts@2x.png
  - name: Pocket Casts
    url: https://pca.st/qwgikqft
    img: pocket_casts@2x.png
  - name: Breaker
    url: https://www.breaker.audio/use-case-1
    img: breaker@2x.png
  - name: Castbox
    url: https://castbox.fm/channel/Use-Case-id2386856
    img: castbox@2x.png
  - name: RadioPublic
    url: https://radiopublic.com/use-case-WdA3q7
    img: radiopublic@2x.png

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
